name: Deploy Backend

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT || 22 }}
          script: |
            cd sanctity
            git pull origin main

            cd backend

            docker stop backend-container || true
            docker rm backend-container || true

            docker rmi backend:latest || true

            docker build -t backend:latest .

            docker run -d \
              --name backend-container \
              -p 5000:5000 \
              -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              --restart unless-stopped \
              backend:latest

            docker image prune -f
